development:
  adapter: postgresql
  encoding: unicode
  database: hackstarter_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hackstarter_test
  pool: 5
  host: localhost


